-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO activity_entries (actor_id, entity_type, entity_id, action, summary, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:actor_id, :entity_type, :entity_id, :action, :summary, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    actor_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.actor_id ELSE activity_entries.actor_id END,
    entity_type = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.entity_type ELSE activity_entries.entity_type END,
    entity_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.entity_id ELSE activity_entries.entity_id END,
    action = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.action ELSE activity_entries.action END,
    summary = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.summary ELSE activity_entries.summary END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.household_id ELSE activity_entries.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN excluded.updated_by ELSE activity_entries.updated_by END,
    deleted_at = COALESCE(activity_entries.deleted_at, excluded.deleted_at),
    updated_at = MAX(activity_entries.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
        THEN 0 ELSE activity_entries.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND activity_entries.deleted_at IS NULL);
