-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO categories (name, color_hex, icon, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:name, :color_hex, :icon, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    name = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN excluded.name ELSE categories.name END,
    color_hex = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN excluded.color_hex ELSE categories.color_hex END,
    icon = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN excluded.icon ELSE categories.icon END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN excluded.household_id ELSE categories.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN excluded.updated_by ELSE categories.updated_by END,
    deleted_at = COALESCE(categories.deleted_at, excluded.deleted_at),
    updated_at = MAX(categories.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
        THEN 0 ELSE categories.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND categories.deleted_at IS NULL);
