-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO households (name, invite_code, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:name, :invite_code, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    name = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
        THEN excluded.name ELSE households.name END,
    invite_code = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
        THEN excluded.invite_code ELSE households.invite_code END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
        THEN excluded.updated_by ELSE households.updated_by END,
    deleted_at = COALESCE(households.deleted_at, excluded.deleted_at),
    updated_at = MAX(households.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
        THEN 0 ELSE households.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND households.deleted_at IS NULL);
