-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO occurrence_completions (task_id, occurrence, completed_by, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:task_id, :occurrence, :completed_by, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    task_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN excluded.task_id ELSE occurrence_completions.task_id END,
    occurrence = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN excluded.occurrence ELSE occurrence_completions.occurrence END,
    completed_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN excluded.completed_by ELSE occurrence_completions.completed_by END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN excluded.household_id ELSE occurrence_completions.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN excluded.updated_by ELSE occurrence_completions.updated_by END,
    deleted_at = COALESCE(occurrence_completions.deleted_at, excluded.deleted_at),
    updated_at = MAX(occurrence_completions.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
        THEN 0 ELSE occurrence_completions.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND occurrence_completions.deleted_at IS NULL);
