-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO packing_templates (name, items, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:name, :items, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    name = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
        THEN excluded.name ELSE packing_templates.name END,
    items = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
        THEN excluded.items ELSE packing_templates.items END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
        THEN excluded.household_id ELSE packing_templates.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
        THEN excluded.updated_by ELSE packing_templates.updated_by END,
    deleted_at = COALESCE(packing_templates.deleted_at, excluded.deleted_at),
    updated_at = MAX(packing_templates.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
        THEN 0 ELSE packing_templates.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND packing_templates.deleted_at IS NULL);
