-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO reminders (task_id, offset_minutes, kind, latitude, longitude, radius_meters, on_enter, on_exit, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:task_id, :offset_minutes, :kind, :latitude, :longitude, :radius_meters, :on_enter, :on_exit, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    task_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.task_id ELSE reminders.task_id END,
    offset_minutes = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.offset_minutes ELSE reminders.offset_minutes END,
    kind = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.kind ELSE reminders.kind END,
    latitude = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.latitude ELSE reminders.latitude END,
    longitude = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.longitude ELSE reminders.longitude END,
    radius_meters = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.radius_meters ELSE reminders.radius_meters END,
    on_enter = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.on_enter ELSE reminders.on_enter END,
    on_exit = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.on_exit ELSE reminders.on_exit END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.household_id ELSE reminders.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN excluded.updated_by ELSE reminders.updated_by END,
    deleted_at = COALESCE(reminders.deleted_at, excluded.deleted_at),
    updated_at = MAX(reminders.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
        THEN 0 ELSE reminders.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND reminders.deleted_at IS NULL);
