-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO shopping_items (title, quantity, is_bought, category_id, added_by, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:title, :quantity, :is_bought, :category_id, :added_by, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    title = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.title ELSE shopping_items.title END,
    quantity = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.quantity ELSE shopping_items.quantity END,
    is_bought = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.is_bought ELSE shopping_items.is_bought END,
    category_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.category_id ELSE shopping_items.category_id END,
    added_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.added_by ELSE shopping_items.added_by END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.household_id ELSE shopping_items.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN excluded.updated_by ELSE shopping_items.updated_by END,
    deleted_at = COALESCE(shopping_items.deleted_at, excluded.deleted_at),
    updated_at = MAX(shopping_items.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
        THEN 0 ELSE shopping_items.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND shopping_items.deleted_at IS NULL);
