-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO subtasks (task_id, title, is_done, sort_order, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:task_id, :title, :is_done, :sort_order, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    task_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.task_id ELSE subtasks.task_id END,
    title = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.title ELSE subtasks.title END,
    is_done = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.is_done ELSE subtasks.is_done END,
    sort_order = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.sort_order ELSE subtasks.sort_order END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.household_id ELSE subtasks.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN excluded.updated_by ELSE subtasks.updated_by END,
    deleted_at = COALESCE(subtasks.deleted_at, excluded.deleted_at),
    updated_at = MAX(subtasks.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
        THEN 0 ELSE subtasks.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND subtasks.deleted_at IS NULL);
