-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO tasks (title, notes, starts_at, duration_minutes, is_all_day, location_name, latitude, longitude, rrule, recurrence_exceptions, assignee_id, created_by, category_id, completed_at, travel_mode, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:title, :notes, :starts_at, :duration_minutes, :is_all_day, :location_name, :latitude, :longitude, :rrule, :recurrence_exceptions, :assignee_id, :created_by, :category_id, :completed_at, :travel_mode, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    title = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.title ELSE tasks.title END,
    notes = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.notes ELSE tasks.notes END,
    starts_at = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.starts_at ELSE tasks.starts_at END,
    duration_minutes = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.duration_minutes ELSE tasks.duration_minutes END,
    is_all_day = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.is_all_day ELSE tasks.is_all_day END,
    location_name = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.location_name ELSE tasks.location_name END,
    latitude = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.latitude ELSE tasks.latitude END,
    longitude = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.longitude ELSE tasks.longitude END,
    rrule = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.rrule ELSE tasks.rrule END,
    recurrence_exceptions = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.recurrence_exceptions ELSE tasks.recurrence_exceptions END,
    assignee_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.assignee_id ELSE tasks.assignee_id END,
    created_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.created_by ELSE tasks.created_by END,
    category_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.category_id ELSE tasks.category_id END,
    completed_at = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.completed_at ELSE tasks.completed_at END,
    travel_mode = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.travel_mode ELSE tasks.travel_mode END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.household_id ELSE tasks.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN excluded.updated_by ELSE tasks.updated_by END,
    deleted_at = COALESCE(tasks.deleted_at, excluded.deleted_at),
    updated_at = MAX(tasks.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
        THEN 0 ELSE tasks.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND tasks.deleted_at IS NULL);
