-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.

INSERT INTO users (display_name, color, household_id, id, created_at, updated_at, updated_by, deleted_at, dirty)
VALUES (:display_name, :color, :household_id, :id, :created_at, :updated_at, :updated_by, :deleted_at, 0)
ON CONFLICT(id) DO UPDATE SET
    display_name = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
        THEN excluded.display_name ELSE users.display_name END,
    color = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
        THEN excluded.color ELSE users.color END,
    household_id = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
        THEN excluded.household_id ELSE users.household_id END,
    updated_by = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
        THEN excluded.updated_by ELSE users.updated_by END,
    deleted_at = COALESCE(users.deleted_at, excluded.deleted_at),
    updated_at = MAX(users.updated_at, excluded.updated_at),
    dirty = CASE WHEN (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
        THEN 0 ELSE users.dirty END
WHERE (excluded.updated_at, COALESCE(excluded.updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
    OR (excluded.deleted_at IS NOT NULL AND users.deleted_at IS NULL);
