-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'activity_entry',
    activity_entries.id,
    json_object('actor_id', activity_entries.actor_id, 'entity_type', activity_entries.entity_type, 'entity_id', activity_entries.entity_id, 'action', activity_entries.action, 'summary', activity_entries.summary, 'deleted_at', activity_entries.deleted_at),
    json_object('actor_id', :actor_id, 'entity_type', :entity_type, 'entity_id', :entity_id, 'action', :action, 'summary', :summary, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM activity_entries
WHERE activity_entries.id = :id
    -- The row being replaced is this person's own writing.
    AND activity_entries.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (activity_entries.updated_at, COALESCE(activity_entries.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (activity_entries.actor_id IS NOT :actor_id
           OR activity_entries.entity_type IS NOT :entity_type
           OR activity_entries.entity_id IS NOT :entity_id
           OR activity_entries.action IS NOT :action
           OR activity_entries.summary IS NOT :summary
           OR activity_entries.deleted_at IS NOT :deleted_at);
