-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'category',
    categories.id,
    json_object('name', categories.name, 'color_hex', categories.color_hex, 'icon', categories.icon, 'deleted_at', categories.deleted_at),
    json_object('name', :name, 'color_hex', :color_hex, 'icon', :icon, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM categories
WHERE categories.id = :id
    -- The row being replaced is this person's own writing.
    AND categories.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (categories.updated_at, COALESCE(categories.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (categories.name IS NOT :name
           OR categories.color_hex IS NOT :color_hex
           OR categories.icon IS NOT :icon
           OR categories.deleted_at IS NOT :deleted_at);
