-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'household',
    households.id,
    json_object('name', households.name, 'invite_code', households.invite_code, 'deleted_at', households.deleted_at),
    json_object('name', :name, 'invite_code', :invite_code, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM households
WHERE households.id = :id
    -- The row being replaced is this person's own writing.
    AND households.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (households.updated_at, COALESCE(households.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (households.name IS NOT :name
           OR households.invite_code IS NOT :invite_code
           OR households.deleted_at IS NOT :deleted_at);
