-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'occurrence_completion',
    occurrence_completions.id,
    json_object('task_id', occurrence_completions.task_id, 'occurrence', occurrence_completions.occurrence, 'completed_by', occurrence_completions.completed_by, 'deleted_at', occurrence_completions.deleted_at),
    json_object('task_id', :task_id, 'occurrence', :occurrence, 'completed_by', :completed_by, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM occurrence_completions
WHERE occurrence_completions.id = :id
    -- The row being replaced is this person's own writing.
    AND occurrence_completions.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (occurrence_completions.updated_at, COALESCE(occurrence_completions.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (occurrence_completions.task_id IS NOT :task_id
           OR occurrence_completions.occurrence IS NOT :occurrence
           OR occurrence_completions.completed_by IS NOT :completed_by
           OR occurrence_completions.deleted_at IS NOT :deleted_at);
