-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'packing_template',
    packing_templates.id,
    json_object('name', packing_templates.name, 'items', packing_templates.items, 'deleted_at', packing_templates.deleted_at),
    json_object('name', :name, 'items', :items, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM packing_templates
WHERE packing_templates.id = :id
    -- The row being replaced is this person's own writing.
    AND packing_templates.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (packing_templates.updated_at, COALESCE(packing_templates.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (packing_templates.name IS NOT :name
           OR packing_templates.items IS NOT :items
           OR packing_templates.deleted_at IS NOT :deleted_at);
