-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'reminder',
    reminders.id,
    json_object('task_id', reminders.task_id, 'offset_minutes', reminders.offset_minutes, 'kind', reminders.kind, 'latitude', reminders.latitude, 'longitude', reminders.longitude, 'radius_meters', reminders.radius_meters, 'on_enter', reminders.on_enter, 'on_exit', reminders.on_exit, 'deleted_at', reminders.deleted_at),
    json_object('task_id', :task_id, 'offset_minutes', :offset_minutes, 'kind', :kind, 'latitude', :latitude, 'longitude', :longitude, 'radius_meters', :radius_meters, 'on_enter', :on_enter, 'on_exit', :on_exit, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM reminders
WHERE reminders.id = :id
    -- The row being replaced is this person's own writing.
    AND reminders.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (reminders.updated_at, COALESCE(reminders.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (reminders.task_id IS NOT :task_id
           OR reminders.offset_minutes IS NOT :offset_minutes
           OR reminders.kind IS NOT :kind
           OR reminders.latitude IS NOT :latitude
           OR reminders.longitude IS NOT :longitude
           OR reminders.radius_meters IS NOT :radius_meters
           OR reminders.on_enter IS NOT :on_enter
           OR reminders.on_exit IS NOT :on_exit
           OR reminders.deleted_at IS NOT :deleted_at);
