-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'shopping_item',
    shopping_items.id,
    json_object('title', shopping_items.title, 'quantity', shopping_items.quantity, 'is_bought', shopping_items.is_bought, 'category_id', shopping_items.category_id, 'added_by', shopping_items.added_by, 'deleted_at', shopping_items.deleted_at),
    json_object('title', :title, 'quantity', :quantity, 'is_bought', :is_bought, 'category_id', :category_id, 'added_by', :added_by, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM shopping_items
WHERE shopping_items.id = :id
    -- The row being replaced is this person's own writing.
    AND shopping_items.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (shopping_items.updated_at, COALESCE(shopping_items.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (shopping_items.title IS NOT :title
           OR shopping_items.quantity IS NOT :quantity
           OR shopping_items.is_bought IS NOT :is_bought
           OR shopping_items.category_id IS NOT :category_id
           OR shopping_items.added_by IS NOT :added_by
           OR shopping_items.deleted_at IS NOT :deleted_at);
