-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'subtask',
    subtasks.id,
    json_object('task_id', subtasks.task_id, 'title', subtasks.title, 'is_done', subtasks.is_done, 'sort_order', subtasks.sort_order, 'deleted_at', subtasks.deleted_at),
    json_object('task_id', :task_id, 'title', :title, 'is_done', :is_done, 'sort_order', :sort_order, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM subtasks
WHERE subtasks.id = :id
    -- The row being replaced is this person's own writing.
    AND subtasks.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (subtasks.updated_at, COALESCE(subtasks.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (subtasks.task_id IS NOT :task_id
           OR subtasks.title IS NOT :title
           OR subtasks.is_done IS NOT :is_done
           OR subtasks.sort_order IS NOT :sort_order
           OR subtasks.deleted_at IS NOT :deleted_at);
