-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'task',
    tasks.id,
    json_object('title', tasks.title, 'notes', tasks.notes, 'starts_at', tasks.starts_at, 'duration_minutes', tasks.duration_minutes, 'is_all_day', tasks.is_all_day, 'location_name', tasks.location_name, 'latitude', tasks.latitude, 'longitude', tasks.longitude, 'rrule', tasks.rrule, 'recurrence_exceptions', tasks.recurrence_exceptions, 'assignee_id', tasks.assignee_id, 'created_by', tasks.created_by, 'category_id', tasks.category_id, 'completed_at', tasks.completed_at, 'travel_mode', tasks.travel_mode, 'deleted_at', tasks.deleted_at),
    json_object('title', :title, 'notes', :notes, 'starts_at', :starts_at, 'duration_minutes', :duration_minutes, 'is_all_day', :is_all_day, 'location_name', :location_name, 'latitude', :latitude, 'longitude', :longitude, 'rrule', :rrule, 'recurrence_exceptions', :recurrence_exceptions, 'assignee_id', :assignee_id, 'created_by', :created_by, 'category_id', :category_id, 'completed_at', :completed_at, 'travel_mode', :travel_mode, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM tasks
WHERE tasks.id = :id
    -- The row being replaced is this person's own writing.
    AND tasks.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (tasks.updated_at, COALESCE(tasks.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (tasks.title IS NOT :title
           OR tasks.notes IS NOT :notes
           OR tasks.starts_at IS NOT :starts_at
           OR tasks.duration_minutes IS NOT :duration_minutes
           OR tasks.is_all_day IS NOT :is_all_day
           OR tasks.location_name IS NOT :location_name
           OR tasks.latitude IS NOT :latitude
           OR tasks.longitude IS NOT :longitude
           OR tasks.rrule IS NOT :rrule
           OR tasks.recurrence_exceptions IS NOT :recurrence_exceptions
           OR tasks.assignee_id IS NOT :assignee_id
           OR tasks.created_by IS NOT :created_by
           OR tasks.category_id IS NOT :category_id
           OR tasks.completed_at IS NOT :completed_at
           OR tasks.travel_mode IS NOT :travel_mode
           OR tasks.deleted_at IS NOT :deleted_at);
