-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Records an edit this person made that an arriving row is about to replace.
--
-- Runs immediately before the matching apply statement, while the row it is
-- about to lose is still there. It fires only when the stored row is this
-- person's own work, the arriving one is not, the arriving one wins, and
-- something a person would notice actually differs.

INSERT INTO superseded_edits (entity_type, entity_id, mine, theirs, actor_id, superseded_at)
SELECT
    'user',
    users.id,
    json_object('display_name', users.display_name, 'color', users.color, 'deleted_at', users.deleted_at),
    json_object('display_name', :display_name, 'color', :color, 'deleted_at', :deleted_at),
    :updated_by,
    :updated_at
FROM users
WHERE users.id = :id
    -- The row being replaced is this person's own writing.
    AND users.updated_by = :current_user_id
    AND COALESCE(:updated_by, '') <> :current_user_id
    -- The arriving row wins, by the same rule the apply statement uses.
    AND (:updated_at, COALESCE(:updated_by, ''))
        > (users.updated_at, COALESCE(users.updated_by, ''))
    -- And it actually changes something worth telling someone about.
    AND (users.display_name IS NOT :display_name
           OR users.color IS NOT :color
           OR users.deleted_at IS NOT :deleted_at);
