"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 13:55:51.008208
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


travel_mode = postgresql.ENUM(
    "none", "walking", "driving", "transit", name="travel_mode", create_type=False
)
reminder_kind = postgresql.ENUM(
    "fixed", "leave_time", "geo", name="reminder_kind", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    travel_mode.create(bind, checkfirst=False)
    reminder_kind.create(bind, checkfirst=False)
    op.create_table('change_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_change_log'))
    )
    op.create_index('ix_change_log_household_id_seq', 'change_log', ['household_id', 'seq'], unique=False)
    op.create_table('households',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_index('uq_households_invite_code_live', 'households', ['invite_code'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color_hex', sa.String(length=9), server_default='#8E8E93', nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_categories_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_household_id_updated_at', 'categories', ['household_id', 'updated_at'], unique=False)
    op.create_table('packing_templates',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_packing_templates_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packing_templates'))
    )
    op.create_index('ix_packing_templates_household_id_updated_at', 'packing_templates', ['household_id', 'updated_at'], unique=False)
    op.create_table('users',
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=9), server_default='#3478F6', nullable=False),
    sa.Column('apns_token', sa.Text(), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_users_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_household_id_updated_at', 'users', ['household_id', 'updated_at'], unique=False)
    op.create_table('activity_entries',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_entries_actor_id_users'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_activity_entries_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_entries'))
    )
    op.create_index('ix_activity_entries_entity_type_entity_id', 'activity_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_activity_entries_household_id_created_at', 'activity_entries', ['household_id', 'created_at'], unique=False)
    op.create_table('shopping_items',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('is_bought', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_shopping_items_added_by_users'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_shopping_items_category_id_categories'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_shopping_items_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items'))
    )
    op.create_index('ix_shopping_items_category_id', 'shopping_items', ['category_id'], unique=False)
    op.create_index('ix_shopping_items_household_id_updated_at', 'shopping_items', ['household_id', 'updated_at'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rrule', sa.Text(), nullable=True),
    sa.Column('recurrence_exceptions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('travel_mode', travel_mode, server_default='none', nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tasks_category_id_categories'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_tasks_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('ix_tasks_category_id', 'tasks', ['category_id'], unique=False)
    op.create_index('ix_tasks_household_id_starts_at', 'tasks', ['household_id', 'starts_at'], unique=False)
    op.create_index('ix_tasks_household_id_updated_at', 'tasks', ['household_id', 'updated_at'], unique=False)
    op.create_table('reminders',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', reminder_kind, server_default='fixed', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('on_enter', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('on_exit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_reminders_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_reminders_task_id_tasks'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index('ix_reminders_household_id_updated_at', 'reminders', ['household_id', 'updated_at'], unique=False)
    op.create_index('ix_reminders_task_id', 'reminders', ['task_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_subtasks_household_id_households'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_subtasks_task_id_tasks'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtasks'))
    )
    op.create_index('ix_subtasks_household_id_updated_at', 'subtasks', ['household_id', 'updated_at'], unique=False)
    op.create_index('ix_subtasks_task_id_sort_order', 'subtasks', ['task_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtasks_task_id_sort_order', table_name='subtasks')
    op.drop_index('ix_subtasks_household_id_updated_at', table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index('ix_reminders_task_id', table_name='reminders')
    op.drop_index('ix_reminders_household_id_updated_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_tasks_household_id_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_household_id_starts_at', table_name='tasks')
    op.drop_index('ix_tasks_category_id', table_name='tasks')
    op.drop_index('ix_tasks_assignee_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_shopping_items_household_id_updated_at', table_name='shopping_items')
    op.drop_index('ix_shopping_items_category_id', table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index('ix_activity_entries_household_id_created_at', table_name='activity_entries')
    op.drop_index('ix_activity_entries_entity_type_entity_id', table_name='activity_entries')
    op.drop_table('activity_entries')
    op.drop_index('ix_users_household_id_updated_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_packing_templates_household_id_updated_at', table_name='packing_templates')
    op.drop_table('packing_templates')
    op.drop_index('ix_categories_household_id_updated_at', table_name='categories')
    op.drop_table('categories')
    op.drop_index('uq_households_invite_code_live', table_name='households', postgresql_where='deleted_at IS NULL')
    op.drop_table('households')
    op.drop_index('ix_change_log_household_id_seq', table_name='change_log')
    op.drop_table('change_log')
    bind = op.get_bind()
    reminder_kind.drop(bind, checkfirst=False)
    travel_mode.drop(bind, checkfirst=False)
    # ### end Alembic commands ###
