"""Declarative base and the column set every synchronised entity carries.

Rows are never deleted physically: `deleted_at` marks a tombstone and the row
stays so the deletion can propagate to a device that has been offline. The
client-only `dirty` flag has no counterpart here — the server never needs it.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Predictable constraint names keep autogenerated migrations stable.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def sync_fk(target: str) -> ForeignKey:
    """A deferrable foreign key.

    A push carries one batch of rows of every type at once, and the client has
    no reason to order them by dependency. Deferring the check to COMMIT lets a
    task and the category it points at arrive in any order inside the same
    transaction.
    """
    return ForeignKey(target, deferrable=True, initially="DEFERRED")


def uuid_column(**kwargs) -> Mapped[uuid.UUID]:
    return mapped_column(PgUUID(as_uuid=True), **kwargs)


class SyncMixin:
    """Columns shared by every synchronised entity."""

    # Generated on the device, never by the database.
    id: Mapped[uuid.UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    # Written by the client clock; the basis for last-write-wins.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    # Author of the last write. Tie-breaks equal `updated_at` deterministically
    # and gives the activity feed its actor. Deliberately not a foreign key:
    # households reference users and users reference households, and a cycle of
    # required constraints would only make writes harder to order.
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True), nullable=True
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )


class HouseholdScopedMixin(SyncMixin):
    """Everything a household owns. Pull filters on this column."""

    @declared_attr
    @classmethod
    def household_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            PgUUID(as_uuid=True), sync_fk("households.id"), nullable=False
        )
