#!/usr/bin/env python3
"""Generate the device's change-applying SQL from the schema.

The device resolves conflicts too. A row arriving from a pull can be older than
an edit the user made while offline and has not pushed yet, and applying it
blindly would throw that edit away. So the same two rules run on both sides:
last-write-wins on `updated_at` with `updated_by` as the tie-break, and
deletion wins unconditionally.

Rather than writing those rules twice — once in Swift and once in whatever
tests them — the SQL is generated here, committed, and executed verbatim by
both. `tests/test_generated_sql.py` fails if the committed files stop matching
what this script produces.

Run: python tools/generate_client_sql.py
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))

from app.sync.registry import SPECS_BY_TYPE  # noqa: E402

OUTPUT = ROOT / "ios/FamilyCalendarKit/Sources/FamilyCalendarKit/Database/SQL/apply"

BANNER = """-- Generated by tools/generate_client_sql.py — do not edit by hand.
--
-- Applies one row pulled from the server to the device database.
--
-- Timestamps compare as text on purpose: every timestamp on the wire is RFC
-- 3339, UTC, with milliseconds, and in that one fixed shape lexicographic order
-- is chronological order. A value written any other way would silently sort
-- wrong, which is why Timestamp.swift has only one writer.
"""

#: The device's own bookkeeping, never sent by the server.
CLIENT_ONLY = ("dirty",)

#: Decided by their own rules below, not by the generic last-write-wins copy.
SPECIAL = ("deleted_at", "updated_at", "dirty", "id", "created_at")


def wins_clause(table: str) -> str:
    """True when the incoming row supersedes the stored one.

    A row-value comparison says both halves of last-write-wins at once: newer
    `updated_at` wins, and an equal one is broken by `updated_by`, which two
    devices with the same clock reading will still order the same way.
    """
    return (
        "(excluded.updated_at, COALESCE(excluded.updated_by, ''))\n"
        f"        > ({table}.updated_at, COALESCE({table}.updated_by, ''))"
    )


def statement_for(entity_type: str) -> str:
    table = SPECS_BY_TYPE[entity_type].table
    name = table.name
    columns = [column.name for column in table.columns]
    wins = wins_clause(name)

    insert_columns = columns + list(CLIENT_ONLY)
    # A row that just arrived from the server is not waiting to be sent back.
    values = [f":{column}" for column in columns] + ["0"]

    assignments = [
        f"    {column} = CASE WHEN {wins}\n        THEN excluded.{column} ELSE {name}.{column} END"
        for column in columns
        if column not in SPECIAL
    ]
    assignments.append(
        f"    deleted_at = COALESCE({name}.deleted_at, excluded.deleted_at)"
    )
    assignments.append(f"    updated_at = MAX({name}.updated_at, excluded.updated_at)")
    # Losing to the incoming row means the local edit is gone, so there is
    # nothing left to push. Winning means the edit still has to go out.
    assignments.append(
        f"    dirty = CASE WHEN {wins}\n        THEN 0 ELSE {name}.dirty END"
    )

    return (
        f"{BANNER}\n"
        f"INSERT INTO {name} ({', '.join(insert_columns)})\n"
        f"VALUES ({', '.join(values)})\n"
        f"ON CONFLICT(id) DO UPDATE SET\n"
        + ",\n".join(assignments)
        + "\n"
        f"WHERE {wins}\n"
        f"    OR (excluded.deleted_at IS NOT NULL AND {name}.deleted_at IS NULL);\n"
    )


def generate() -> dict[str, str]:
    return {
        entity_type: statement_for(entity_type)
        for entity_type in sorted(SPECS_BY_TYPE)
    }


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for entity_type, sql in generate().items():
        path = OUTPUT / f"{entity_type}.sql"
        path.write_text(sql)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
